import type { Copy } from './types'

export const en: Copy = {
  lang: 'en',
  dateLong: 'Saturday, 10 October 2026',
  deadlineLong: '26 September',
  events: {
    akad: { name: 'Akad Nikah', timeLine: '08.00 WIB' },
    resepsi: {
      name: 'Resepsi',
      timeLine: '18.30 WIB onwards',
      directions: [
        'Parking: go straight to P7, P8 or P9.',
        'Drop-off: go straight to P9. Please do not drop off at the MGK lobby.',
      ],
    },
  },
  places: (pax) => (pax === 1 ? 'We have kept a place in your name.' : `We have kept ${pax} places in your name.`),
  openMaps: 'Open in Maps',

  letter: {
    dear: 'DEAR',
    invitedTo: 'you are invited to the wedding of',
    and: 'and',
    replyBy: (d) => `Kindly reply by ${d}`,
    aria: (name) => `A letter addressed to ${name}`,
    open: 'Open the invitation',
  },
  cover: {
    title: 'The wedding of Sita & Fatan',
    drag: 'Drag the letter up to open',
    tap: 'or tap here to open',
    scrollCue: 'Scroll down to continue',
  },
  verse: {
    text: 'It is He who created you from one soul and created from it its mate, that he might dwell in security with her.',
    source: 'Al-A’raf : 189',
  },
  vow: [
    ['We found', 'in each'],
    ['other a', 'home we'],
    ['never knew', 'we were'],
    ['looking for,', 'a quiet'],
    ['place where', 'the day'],
    ['ends and', 'begins.'],
  ],
  couple: {
    // Worded as the approved WhatsApp template has it: Mr./Mrs. in English.
    brideParents: 'Daughter of Mr. Siswoko & Mrs. Icha Siti Hapsah',
    groomParents: 'Son of Mr. Sabrul Jamil & Mrs. Yudhanti Dwi Lestari',
    and: 'and',
    captions: { bride: ['the', 'Bride'], both: ['the', 'Two'], groom: ['the', 'Groom'] },
    aria: 'Bride and groom',
  },
  countdown: {
    units: ['days', 'hours', 'minutes', 'seconds'],
    over: ['Thank you for ', 'being there.'],
    addToCalendar: 'Add to calendar',
    dateAria: '10 October 2026',
  },
  dress: {
    title: 'Formal, in dark tones.',
    lines: ['Black, brown or grey.', 'We would truly appreciate it if you could dress to the code.'],
    example: 'Examples only. Anything in these tones is right.',
    drag: 'Drag to turn',
    tones: ['Black', 'Brown', 'Grey'],
    toneAria: 'Tone',
    aria: 'Dress code',
  },
  gallery: { hint: 'Scroll to wander' },
  gift: {
    label: 'Gift',
    title: ['Only if you ', 'wish.'],
    presence: 'Your presence is the gift. The card carries the rest.',
    intro: 'Your presence is the gift. If you would like to send something anyway:',
    withLove: 'with love,',
    turnOver: 'TURN OVER',
    turn: 'Turn the card over',
    turnBack: 'Turn it back',
    copy: 'Copy account number',
    copied: 'Copied',
    drag: 'Drag the card to turn it',
    aria: (bank, account, holder) => `Gift card: ${bank} ${account}, ${holder}`,
  },
  rsvp: {
    crumb: 'RSVP',
    of: (i, n) => `${i} of ${n}`,
    askBefore: 'Will you join us at the ',
    askAfter: '?',
    yes: 'Yes, I’ll be there',
    no: 'Sadly, I can’t',
    later: 'I’ll answer later, let me keep reading',
    howMany: ['How many of you ', 'are coming?'],
    kept: (n) => `We kept ${n} places for you.`,
    fewer: 'Fewer',
    more: 'More',
    count: 'Number of guests',
    ok: 'OK',
    enter: 'press Enter ↵',
    reviewEyebrow: 'One last look',
    reviewQ: ['Does this look ', 'right?'],
    coming: 'Coming',
    ofYou: (n) => `${n} of you`,
    notAble: 'Not able to make it',
    sending: 'Sending…',
    send: 'Send my reply',
    doneEyebrow: 'Reply received',
    seeYou: ['See you on ', '10 October.'],
    miss: ['We’ll ', 'miss you.'],
    lastPage: 'Thank you. One last page below.',
    keep: 'Keep exploring ↓',
    change: 'Change my answer',
    answerToContinue: 'Answer to continue',
    prev: 'Previous question',
    next: 'Next question',
    nav: 'Move between questions',
    aria: 'RSVP',
  },
  closing: {
    thanks: 'thank you for being part of our day.',
    signOff: 'With all our love,',
    reply: 'Reply to the invitation',
    aria: 'Closing',
  },
  chrome: {
    mute: 'Mute music',
    unmute: 'Unmute music',
    pill: 'RSVP',
    loading: 'Loading your invitation',
    switchTo: 'Bahasa Indonesia',
  },
}
